# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spark/connect/ml.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyspark.sql.connect.proto import expressions_pb2 as spark_dot_connect_dot_expressions__pb2
from pyspark.sql.connect.proto import relations_pb2 as spark_dot_connect_dot_relations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16spark/connect/ml.proto\x12\x10spark.connect.ml\x1a\x1fspark/connect/expressions.proto\x1a\x1dspark/connect/relations.proto"~\n\x08Pipeline\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12/\n\x06stages\x18\x02 \x03(\x0b\x32\x17.spark.connect.ml.StageR\x06stages\x12-\n\x05input\x18\x03 \x01(\x0b\x32\x17.spark.connect.RelationR\x05input"R\n\rPipelineModel\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12-\n\x05input\x18\x02 \x01(\x0b\x32\x17.spark.connect.RelationR\x05input"\xc6\x01\n\x05Stage\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12G\n\nparameters\x18\x02 \x03(\x0b\x32\'.spark.connect.ml.Stage.ParametersEntryR\nparameters\x1a`\n\x0fParametersEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32!.spark.connect.Expression.LiteralR\x05value:\x02\x38\x01\x42M\n\x1eorg.apache.spark.connect.protoP\x01Z)github.com/databricks/spark-connect/protob\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "spark.connect.ml_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036org.apache.spark.connect.protoP\001Z)github.com/databricks/spark-connect/proto"
    )
    _STAGE_PARAMETERSENTRY._options = None
    _STAGE_PARAMETERSENTRY._serialized_options = b"8\001"
    _PIPELINE._serialized_start = 108
    _PIPELINE._serialized_end = 234
    _PIPELINEMODEL._serialized_start = 236
    _PIPELINEMODEL._serialized_end = 318
    _STAGE._serialized_start = 321
    _STAGE._serialized_end = 519
    _STAGE_PARAMETERSENTRY._serialized_start = 423
    _STAGE_PARAMETERSENTRY._serialized_end = 519
# @@protoc_insertion_point(module_scope)
